CREATE TABLE IF NOT EXISTS [queues](
    [id] BIGINT PRIMARY KEY NOT NULL UNIQUE,
    [title] VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS [downloads](
    [id] BIGINT PRIMARY KEY NOT NULL UNIQUE,
    [title] VARCHAR(512),
    [queue] BIGINT DEFAULT 1 REFERENCES [queues]([id]) ON DELETE SET NULL ON UPDATE SET NULL,
    [url] TEXT NOT NULL,
    [save_path] TEXT NOT NULL,
    [file_size] VARCHAR(255) DEFAULT "-",
    [created_at] TIMESTAMP DEFAULT CURREMT_TIMESTAMP,
    [pause_able] TINYINT(1) DEFAULT 0
    [status] TINYINT DEFAULT 0);